language: bash

services:
  - docker

before_install:
- docker build -t thanakijwanavit/jupyter_cuda_datascience .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- docker push thanakijwanavit/jupyter_cuda_datascience
